name: MythicLibExt
main: cc.mewcraft.mythiclibext.MythicLibExt
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    MythicLib:
      load: BEFORE
      required: true
      join-classpath: true
    MMOItems:
      load: AFTER
      required: false
      join-classpath: false
    ItemsAdder:
      load: OMIT
      required: true
      join-classpath: true
