name: MythicLibExt
main: cc.mewcraft.mythiclibext.MythicLibExt
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
load-before:
  - name: MMOItems
load-after:
  - name: helper
  - name: MewCore
  - name: MythicLib
dependencies:
  - name: helper
    required: true
  - name: MewCore
    required: true
  - name: MythicLib
    required: false
  - name: ItemsAdder
    required: false
