##################
# 通用设置
##################

# 在控制台显示更多信息？
debug: true

##################
# 召唤物设置
##################

# 召唤物列表，注意缩进
items:
  # 随便什么都行，但必须唯一
  # 如果写数字，必须用引号括起来
  a:
    # ItemsAdder 的物品ID，必须唯一
    itemID: rpgitems:egg_deathknight
    # 怪物在 MM 配置文件里的内置 ID
    mobID: boss_死亡骑士
    # MM 怪物的等级
    mobLevel: 1
    # 在使用召唤物后，产生怪物的延迟，单位刻
    delaySpawn: 100
    # 使用召唤物后产生的效果
    effects:
      # 在召唤地点产生爆炸
      #   可以用来掩盖使用怪物蛋原本的声音
      explosion:
        # 爆炸的威力
        #   参考 https://minecraft.fandom.com/zh/wiki/%E7%88%86%E7%82%B8
        power: 1.0
        # 爆炸延迟，单位刻
        #   在真正的爆炸发生前，会有持续性的假爆炸
        delay: 100
      # 声音效果
      sounds:
        # 声音名字的命名空间
        #   参考 Minecraft 原版指令 /playsound
        #   或者 wiki 中每个词条下的「音效介绍」表格
        - name: minecraft:entity.wither.spawn
          # 声源，告诉玩家声音来自哪里
          #   可用的值 [voice, music, hostile, record, weather, neutral, block, ambient, master, player]
          source: master
          # 声调，范围 0f ~ 2f
          #   1 为正常，0 变低，2 变高
          pitch: 1.0
          # 声音大小，范围 0f ~ ∞
          #   注意声音大小影响的是收听距离
          #   收听距离 = volume * 16
          volume: 6.25
          # 声音延迟，单位刻
          #   最好设置成跟 delaySpawn 一样
          delay: 100
      # 药水效果 **注意** 下列选项要么全写，要么全不写，否则会报错
      potions:
        # 药水效果类型参考 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
        - type: blindness
          # 效果强度，从 0 开始
          amplifier: 3
          # 效果时间，单位刻
          duration: 120
          # 产生半透明粒子
          ambient: true
          # 开启粒子效果
          particles: true
          # 在状态栏显示图标
          icon: false
          # 效果半径，将应用到半径内的所有玩家
          radius: 100
        # 药水效果可以写多个
        - type: slow
          amplifier: 3
          duration: 100
          ambient: true
          particles: true
          icon: false
          radius: 100
    # 使用召唤物的前提条件
    conditions:
      # 可以在哪些世界召唤
      #   名字**区分**大小写
      worlds:
        - ex_nether
      # 可以在哪些生物群系召唤
      #   名字**不区分**大小写
      #   群系名字参考 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
      biomes:
        - basalt_deltas
        - nether_wastes
      # 可以在什么高度范围召唤
      #   范围必须在 -64 和 320 之间
      height:
        min: 32
        max: 80
      # 召唤所需要的开放空间（长方体）
      #   长方体的底面所在高度 = 玩家拿物品点击地面的所在高度 + 1
      #   长方体的长和宽一样 = radius * 2 + 1
      #   不要设置得太高，会导致崩服
      #   全部写 0 则关闭该检测
      space:
        # 空间的半径。以玩家拿物品点击地面的所在坐标为中心
        radius: 8
        # 空间的高度
        height: 16
      # 召唤冷却时间，单位秒
      #   冷却时间对于每个玩家、每个召唤物独立计算
      #   重载插件会导致所有的冷却重置，以后会改进
      cooldown: 30
      # 是否必须在荒郊野外
      #   需要安装 Towny
      wilderness: true
      # 防止在指定半径范围内召唤多只怪物
      #   写 0 则关闭该检测
      checkActive: 200