name: MMOExt
main: co.mcsky.mmoext.Main
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
load-before: [ ]
load-after:
  - name: helper
  - name: MewCore
dependencies:
  - name: helper
    required: true
  - name: MewCore
    required: true
  - name: MythicLib
    required: false
  - name: ItemsAdder
    required: false
  - name: Towny
    required: false
