name: PickaxePower
main: cc.mewcraft.pickaxepower.PickaxePower
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: OMIT
      required: true
      join-classpath: true
    ItemsAdder:
      load: OMIT
      required: true
      join-classpath: true
