name: PickaxePower
main: cc.mewcraft.pickaxepower.PickaxePower
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
load-before: [ ]
load-after:
  - name: helper
  - name: MewCore
dependencies:
  - name: helper
    required: true
  - name: MewCore
    required: true
  - name: ProtocolLib
    required: false
  - name: ItemsAdder
    required: false
  - name: Towny
    required: false
