name: EnchantGui
main: cc.mewcraft.enchantment.gui.EnchantGuiPlugin
version: ${version}
description: ${description}
author: Nailm
api-version: "1.19"
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    Kotlin:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    ExcellentEnchants:
      load: BEFORE
      required: false
      join-classpath: true