[versions]

cloudcmds = "1.8.3"
languages = "1.3-SNAPSHOT"

[libraries]

# the proxy server api
proxy-velocity = { group = "com.velocitypowered", name = "velocity-api", version = "3.2.0-SNAPSHOT" }

# the minecraft server api
server-paper = { group = "io.papermc.paper", name = "paper-api", version = "1.19.4-R0.1-SNAPSHOT" }
server-purpur = { group = "org.purpurmc.purpur", name = "purpur-api", version = "1.19.4-R0.1-SNAPSHOT" }

# deps that need to be shaded
guice = { group = "com.google.inject", name = "guice", version = "5.1.0" }
hikari = { group = "com.zaxxer", name = "HikariCP", version = "5.0.1" }
anvilgui = { group = "net.wesjd", name = "anvilgui", version = "1.6.5-SNAPSHOT" }
cloud-paper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloudcmds" }
cloud-minecraft-extras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloudcmds" }
configurate = { group = "org.spongepowered", name = "configurate-yaml", version = "4.1.2" }
lang-bukkit = { group = "de.themoep.utils", name = "lang-bukkit", version.ref = "languages" }
lang-velocity = { group = "de.themoep.utils", name = "lang-velocity", version.ref = "languages" }
authlib = { group = "com.mojang", name = "authlib", version = "1.5.25" }
evalex = { group = "com.ezylang", name = "EvalEx", version = "3.0.4" }

# deps that present as other plugins
mewcore = { group = "cc.mewcraft", name = "mewcore", version = "latest.release" }
helper = { group = "me.lucko", name = "helper", version = "5.6.13" }
helper-sql = { group = "me.lucko", name = "helper-sql", version = "1.3.2" }
helper-redis = { group = "me.lucko", name = "helper-redis", version = "1.2.1" }
luckperms = { group = "net.luckperms", name = "api", version = "5.4" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7" }
essentials = { group = "net.essentialsx", name = "EssentialsX", version = "2.19.0" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version = "0.99.0.6" }
itemsadder = { group = "com.github.LoneDev6", name = "api-itemsadder", version = "3.4.1-r4" }
mythicmobs = { group = "io.lumine", name = "Mythic-Dist", version = "5.2.6" }
mythiclib = { group = "io.lumine", name = "MythicLib-dist", version = "1.6-SNAPSHOT" }
mmoitems = { group = "net.Indyuce", name = "MMOItems-API", version = "6.9.4-SNAPSHOT" }
interactivebooks = { group = "net.leonardo_dgs", name = "InteractiveBooks", version = "1.6.5" }
brewery = { group = "com.github.DieReicheErethons", name = "Brewery", version = "3.1.1" }
minipapi = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version = "2.1.0" }
papi = { group = "me.clip", name = "placeholderapi", version = "2.11.2" }
gemseco = { group = "me.xanium.gemseconomy", name = "GemsEconomy", version = "1.3.8" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version = "5.0.0" }
connector-core = { group = "de.themoep.connectorplugin", name = "core", version = "1.5-SNAPSHOT" }
connector-bukkit = { group = "de.themoep.connectorplugin", name = "bukkit", version = "1.5-SNAPSHOT" }

# deps only for compile-time checking
checker-qual = { group = "org.checkerframework", name = "checker-qual", version = "3.28.0" }
apiguardian-api = { group = "org.apiguardian", name = "apiguardian-api", version = "1.1.2" }
annotations = { group = "org.jetbrains", name = "annotations", version = "24.0.1" }

# deps only for testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.9.0" }

[bundles]

cmds = ["cloud-paper", "cloud-minecraft-extras"]
checker = ["checker-qual", "apiguardian-api", "annotations"]

[plugins]

indra = { id = "net.kyori.indra", version = "3.1.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.5" }
pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version = "0.5.3" }