name: MewFishing
version: ${version}
description: ${description}
main: cc.mewcraft.mewfishing.MewFishing
api-version: 1.19
authors: [ Nailm ]
dependencies:
  server:
    helper:
      load: BEFORE
    helper-redis:
      load: BEFORE
    MewCore:
      load: BEFORE
    GemsEconomy:
      load: BEFORE
