name: MewFishing
version: ${version}
description: ${description}
main: cc.mewcraft.mewfishing.MewFishing
api-version: 1.19
authors: [ Nailm ]
dependencies:
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    helper-redis:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    GemsEconomy:
      load: OMIT
      required: true
      join-classpath: true
