name: MewFishing
version: ${version}
description: ${description}
main: cc.mewcraft.mewfishing.MewFishing
api-version: 1.19
authors: [ Nailm ]
load-before: [ ]
load-after:
  - name: helper
  - name: MewCore
dependencies:
  - name: helper
    required: true
    bootstrap: false
  - name: MewCore
    required: true
    bootstrap: false
  - name: GemsEconomy
    required: false
    bootstrap: false
