name: ProxyChatBridge
version: ${version}
description: ${description}
main: com.ranull.proxychatbridge.bukkit.ProxyChatBridge
api-version: 1.19
authors: [ Nailm ]
load-before: [ ]
load-after: [ ]
dependencies:
  - name: ChatChat
    required: false
    bootstrap: false
permissions:
  proxychatbridge.command:
    description: Access to the ProxyChatBridge-Bukkit commands
    default: op
