name: ProxyChatBridge
version: ${version}
description: ${description}
main: com.ranull.proxychatbridge.bukkit.ProxyChatBridge
api-version: 1.19
authors: [ Nailm ]
load-before: [ ]
load-after: [ ]
dependencies:
  bootstrap: { }
  server:
    ChatChat:
      load: OMIT
      required: false
      join-classpath: true
