name: MewCore
version: ${version}
description: ${description}
main: cc.mewcraft.mewcore.MewCore
api-version: 1.19
authors: [ Nailm ]
dependencies:
  server:
    helper:
      load: BEFORE
      required: true
    Vault:
      required: false
    Towny:
      required: false
    LuckPerms:
      required: false
    PlaceholderAPI:
      required: false
    ItemsAdder:
      required: false
    MythicLib:
      required: false
    MMOItems:
      required: false
    InteractiveBooks:
      required: false
    Brewery:
      required: false
