name: MewCore
version: ${version}
description: ${description}
main: cc.mewcraft.mewcore.MewCore
api-version: 1.19
authors: [ Nailm ]
dependencies:
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Towny:
      load: OMIT
      required: false
      join-classpath: true
    ItemsAdder:
      load: OMIT
      required: false
      join-classpath: true
    MythicLib:
      load: OMIT
      required: false
      join-classpath: true
    MMOItems:
      load: OMIT
      required: false
      join-classpath: true
    InteractiveBooks:
      load: OMIT
      required: false
      join-classpath: true
    Brewery:
      load: OMIT
      required: false
      join-classpath: true
