name: KeepInv
version: ${version}
description: ${description}
main: cc.mewcraft.keepinv.KeepInv
api-version: 1.19
authors: [ Nailm ]
load-before: [ ]
load-after:
  - name: helper
dependencies:
  - name: helper
    required: true
    bootstrap: false
  - name: Towny
    required: false
    bootstrap: false
  - name: LuckPerms
    required: false
    bootstrap: false
  - name: PlaceholderAPI
    required: false
    bootstrap: false
  - name: ItemsAdder
    required: false
    bootstrap: false
