name: KeepInv
version: ${version}
description: ${description}
main: cc.mewcraft.keepinv.KeepInv
api-version: 1.19
authors: [ Nailm ]
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    Towny:
      load: OMIT
      required: false
      join-classpath: true
    LuckPerms:
      load: OMIT
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: OMIT
      required: false
      join-classpath: true
    ItemsAdder:
      load: OMIT
      required: false
      join-classpath: true
