name: ReforgeGui
main: cc.mewcraft.reforge.gui.ReforgePlugin
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    Reforge:
      load: BEFORE
      required: true
      join-classpath: true
    GemsEconomy:
      load: BEFORE
      required: true
      join-classpath: true

