name: TownyOrigin
version: ${version}
description: ${description}
main: cc.mewcraft.townyorigin.TownyOrigin
api-version: 1.19
authors: [ Nailm ]
dependencies:
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    Towny:
      load: OMIT
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: OMIT
      required: true
      join-classpath: true
    MiniPlaceholders:
      load: OMIT
      required: true
      join-classpath: true
