name: MewHelp
version: ${version}
description: ${description}
main: cc.mewcraft.mewhelp.MewHelp
api-version: 1.19
authors: [ Nailm ]
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
