name: TownyLink
version: ${version}
description: ${description}
main: cc.mewcraft.townylink.TownyLink
loader: cc.mewcraft.townylink.TownyLinkLoader
api-version: 1.19
authors: [ Nailm ]
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    Towny:
      load: OMIT
      required: true
      join-classpath: true
    ConnectorPlugin:
      load: OMIT
      required: false
      join-classpath: true
