# This is the list of schedules.
schedules:

  # Below is an example section of schedule.
  # You can duplicate the section to create more.
  # A general example:
  # <node key>: [The <node key> is the schedule name. Must be unique among all the schedules.]
  #   type: <schedule type> [Schedule type. Available values: BROADCAST, WORLD_RESET, CONSOLE_COMMAND, FILE_CLEANUP]
  #   schedule: "50 11 * * FRI" [Date & time when this schedule will be executed, written in Linux cron expression]
  #   <dedicated setting 1> [This will be corresponding settings depending on the value of <schedule type>]
  #   <dedicated setting 2>
  #           ...
  #   <dedicated setting n>

  broadcast/countdown_10m:
    type: BROADCAST # The <BROADCAST> schedule type broadcasts messages to the whole server.
    cron: "50 11 * * FRI"
    messages: # List of messages to be broadcast, parsed as MiniMessage strings.
      - "<red>WORLD RESET COUNTDOWN 10m"

  broadcast/countdown_5m:
    type: BROADCAST
    cron: "55 11 * * FRI"
    messages:
      - "<red>WORLD RESET COUNTDOWN 5m"

  broadcast/countdown_1m:
    type: BROADCAST
    cron: "59 11 * * FRI"
    messages:
      - "<red>WORLD RESET COUNTDOWN 1m"

  world_reset/resrc:
    type: WORLD_RESET # The <WORLD_RESET> schedule type resets a specified world.
    cron: "0 12 * * FRI"
    world: resrc # The name of the world which will be reset. CASE-SENSITIVE.
    keep_seed: false # Whether to reset the world seed for the world reset.
    pre_commands: # Commands executing before the reset.
      - "worldreset serverlock true"
      - "kick @a The worlds are being reset"
    post_commands: # Commands executing after the reset.
      - "execute in minecraft:overworld run worldborder set 4000"

  world_reset/resrc_nether:
    type: WORLD_RESET
    cron: "1 12 * * FRI"
    world: resrc_nether
    keep_seed: false
    pre_commands: [ ]
    post_commands:
      - "execute in minecraft:the_nether run worldborder set 4000"

  world_reset/resrc_the_end:
    type: WORLD_RESET
    cron: "2 12 * * FRI"
    world: resrc_the_end
    keep_seed: false
    pre_commands: [ ]
    post_commands:
      - "execute in minecraft:the_end run worldborder set 4000"
      - "worldreset serverlock false"

  console_command/random_broadcast:
    type: CONSOLE_COMMAND
    cron: "10 12 * * FRI"
    commands:
      - "say This is a random console command"

  file_cleanup/old_server_logs:
    type: FILE_CLEANUP # The <FILE_CLEANUP> schedule type deletes specified files.
    cron: "0 4 * * FRI"
    paths: # The file paths, derived from the server root.
      - 'logs'
      - 'crash-reports'
