name: MythicMobsExt
main: cc.mewcraft.mythicmobsext.MythicMobsExt
version: ${version}
description: ${description}
author: Nailm
api-version: 1.19
dependencies:
  bootstrap: { }
  server:
    helper:
      load: BEFORE
      required: true
      join-classpath: true
    MewCore:
      load: BEFORE
      required: true
      join-classpath: true
    MythicMobs:
      load: OMIT
      required: true
      join-classpath: true
    MythicLib:
      load: OMIT
      required: true
      join-classpath: true
    MMOItems:
      load: OMIT
      required: true
      join-classpath: true
